### ISSUE TITLE
Where do you put the `.lilypad` directory for a FastAPI application to be authenticated?

### ISSUE THREAD

**Issue by willbakst** [Mirascope/lilypad#67]
### Question

See title

**Comment by brenkao** [comment]
<img width="1355" alt="image" src="https://github.com/user-attachments/assets/45468296-c2f9-4b03-88a3-c48cf2306d6d" />

You should be able to run `lilypad auth` in the root of your application where you run `fastapi run`

**Comment by willbakst** [comment]
You'll need to set the `LILYPAD_PROJECT_DIR` to point to where the `.lilypad` folder lives. Locally, the default settings work, but if `.lilypad` is copied somewhere else (e.g. during deployment), you'll need to update the environment so we know where to load the config.

This will also shortly be a moot point when we implement #70 (since we will no longer need a `.lilypad` folder at all).
