### ISSUE TITLE
Support for non-JSON serializable params

### ISSUE THREAD

**Issue by TruffleClock** [Mirascope/lilypad#76]
### Description

(copying this one over to GH issues)

I get this error with the code below: `Object of type AnthropicClient is not JSON serializable`

Would be great to skip or have a way to support params that can't be serialized!

```
@lilypad.generation()
def fn(data: str, model: LLMClient = DEFAULT_LLM):
    sys_prompt = f"..."
    prompt = f"..."
    res = model.get_completion(prompt=prompt, system_prompt=sys_prompt, temperature=0.0)
    return res
```

**Comment by willbakst** [comment]
I have an initial fix for this implemented, bit during the implementation I realized there are a few downstream effects that we need to consider.

For context, we are planning on implementing synthetic data generation functionality. If an input argument to a generation is no already jsonable (e.g. your `LLMClient` type), then we'll need to block the data generation features unless the user implements some means of representing the object as json so we can generate it.

This will be covered in more detail in the #69 documentation.
